import type { LessonTopic } from '../types';

export const errorControlTopic: LessonTopic = {
  id: 'error-control',
  title: 'Error Detection and Correction',
  description: 'Transmission errors, detection methods, correction strategies, and Hamming code.',
  sections: [
    {
      id: 'transmission-errors',
      title: 'Transmission Errors',
      summary: 'An error occurs when information received does not match what the sender transmitted. Noise can change binary bits while they travel.',
      recallPrompt: 'When has a data-transmission error occurred?',
      recallAnswer: 'When the received information does not match the sender’s transmitted information.',
    },
    {
      id: 'single-bit-error',
      title: 'Single-Bit Error',
      summary: 'A single-bit error changes exactly one bit in a transmitted data unit.',
      recallPrompt: 'How many bits change in a single-bit error?',
      recallAnswer: 'Exactly one bit.',
    },
    {
      id: 'multiple-and-burst-errors',
      title: 'Multiple-Bit and Burst Errors',
      summary: 'A multiple-bit error damages more than one bit. A burst error flips several consecutive bits during transmission.',
      recallPrompt: 'What makes a burst error more specific than a multiple-bit error?',
      recallAnswer: 'The damaged bits in a burst error are consecutive.',
    },
    {
      id: 'simple-parity-check',
      title: 'Simple Parity Check',
      summary: 'Simple parity adds one bit to a data transmission so the total number of 1s follows an odd- or even-parity rule.',
      bullets: ['For the supplied even-parity rule: add 1 when the data has an odd number of 1s, and add 0 when it has an even number.'],
      recallPrompt: 'Under even parity, what bit is added when the data contains an odd number of 1s?',
      recallAnswer: 'A parity bit of 1, making the total number of 1s even.',
    },
    {
      id: 'two-dimensional-parity',
      title: 'Two-Dimensional Parity Check',
      summary: 'Two-dimensional parity calculates check bits for every row and column and sends both sets with the data.',
      recallPrompt: 'Where are parity bits calculated in a two-dimensional parity check?',
      recallAnswer: 'For all rows and all columns.',
    },
    {
      id: 'checksum',
      title: 'Checksum',
      summary: 'A checksum divides data into equal-sized segments and sends a value calculated from their 1s-complement sum.',
      recallPrompt: 'What operation does the supplied checksum method use after dividing data into segments?',
      recallAnswer: 'It calculates the segment sum using 1s complement.',
    },
    {
      id: 'cyclic-redundancy-check',
      title: 'Cyclic Redundancy Check (CRC)',
      summary: 'CRC appends check bits chosen through binary division so the resulting data unit is divisible by a predetermined binary number.',
      bullets: ['No remainder: accept the data unit.', 'A remainder: damage is detected and the data unit is rejected.'],
      recallPrompt: 'What does a nonzero remainder mean during CRC verification?',
      recallAnswer: 'The data unit was damaged during transmission and should be rejected.',
    },
    {
      id: 'backward-error-correction',
      title: 'Backward Error Correction',
      summary: 'After detecting an error, the receiver asks the sender to retransmit the data unit.',
      recallPrompt: 'What action defines backward error correction?',
      recallAnswer: 'The receiver requests retransmission from the sender.',
    },
    {
      id: 'forward-error-correction',
      title: 'Forward Error Correction',
      summary: 'The receiver uses error-correcting code to recover and repair certain detected errors without requesting retransmission.',
      recallPrompt: 'How does forward error correction differ from backward correction?',
      recallAnswer: 'The receiver repairs supported errors itself instead of asking for retransmission.',
    },
    {
      id: 'hamming-code',
      title: 'Hamming Code',
      summary: 'Hamming code adds parity bits to blocks of data so errors in stored or transmitted data can be detected and corrected.',
      examples: ['Hamming(7,4) contains four data bits and three parity bits, for seven total bits.'],
      recallPrompt: 'What do the two values in Hamming(7,4) represent?',
      recallAnswer: 'Seven total bits and four data bits; the remaining three are parity bits.',
    },
    {
      id: 'hamming-redundant-bits',
      title: 'Choosing Hamming Parity Bits',
      summary: 'For d data bits, choose the smallest number p of parity bits that satisfies 2^p >= d + p + 1.',
      bullets: ['Parity bits occupy positions that are powers of two.', 'For seven data bits, four redundant bits occupy positions 1, 2, 4, and 8.'],
      recallPrompt: 'Where are Hamming parity bits placed?',
      recallAnswer: 'At positions that are powers of two: 1, 2, 4, 8, and so on.',
    },
    {
      id: 'hamming-worked-example',
      title: 'Worked Hamming Example',
      summary: 'For the supplied seven-bit data example 1011001, four even-parity bits are inserted and calculated.',
      bullets: [
        'R1 checks positions 1, 3, 5, 7, 9, and 11.',
        'R2 checks positions 2, 3, 6, 7, 10, and 11.',
        'R4 checks positions 4, 5, 6, and 7; R8 checks positions 8, 9, 10, and 11.',
        'The supplied final values are R1 = 0, R2 = 1, R4 = 1, and R8 = 0.',
      ],
      recallPrompt: 'What parity values result in the supplied 1011001 example?',
      recallAnswer: 'R1 = 0, R2 = 1, R4 = 1, and R8 = 0.',
    },
  ],
};
