import type { LessonTopic } from '../types';

export const digitalAnalogTopic: LessonTopic = {
  id: 'digital-analog',
  title: 'Digital vs. Analog',
  description: 'Signal forms, transmission, converters, and modulation techniques.',
  sections: [
    {
      id: 'representing-information',
      title: 'Representing Information',
      summary: 'Digital and analog are two ways to represent, store, and transmit information.',
      bullets: [
        'Analog systems mirror real-world changes with continuous physical quantities such as waves or voltages.',
        'Digital systems represent information with distinct steps or numbers, usually binary 0s and 1s.',
      ],
      recallPrompt: 'What basic distinction separates analog and digital representation?',
      recallAnswer: 'Analog representation is continuous, while digital representation uses discrete values.',
    },
    {
      id: 'digital-signals',
      title: 'Digital Signals',
      summary: 'A digital signal is a sequence of discrete values and can take only a finite set of values at a given time.',
      examples: ['Telecommunications', 'Computers', 'Digital media'],
      recallPrompt: 'Are the possible values of a digital signal continuous or discrete?',
      recallAnswer: 'Discrete; the signal takes values from a finite set.',
    },
    {
      id: 'analog-signals',
      title: 'Analog Signals',
      summary: 'An analog signal varies continuously over time and can take infinitely many values within a range.',
      examples: ['Radio broadcasting', 'Older television systems'],
      recallPrompt: 'What kind of values can an analog signal take within its range?',
      recallAnswer: 'An infinite number of continuously varying values.',
    },
    {
      id: 'digital-transmission',
      title: 'Digital Transmission',
      summary: 'Digital transmission sends information in discrete or binary form using bits composed of 0s and 1s.',
      benefits: ['High accuracy', 'Efficiency', 'Multiplexing', 'Compression', 'Security'],
      recallPrompt: 'In what form does digital transmission send information?',
      recallAnswer: 'As discrete binary bits, using 0s and 1s.',
    },
    {
      id: 'analog-transmission',
      title: 'Analog Transmission',
      summary: 'Analog transmission sends information as a continuous waveform analogous to the original data.',
      benefits: ['Simplicity', 'Signal fidelity', 'Real-time processing'],
      recallPrompt: 'How does analog transmission represent the original information?',
      recallAnswer: 'As a continuous waveform analogous to the original data.',
    },
    {
      id: 'digital-to-analog-converter',
      title: 'Digital-to-Analog Converter (DAC)',
      summary: 'A DAC converts a digital input into a continuous analog output by translating digital values into voltage levels.',
      examples: ['Recreating an audio waveform from stored digital samples.'],
      recallPrompt: 'What direction of conversion does a DAC perform?',
      recallAnswer: 'Digital input to analog output.',
    },
    {
      id: 'analog-to-digital-converter',
      title: 'Analog-to-Digital Converter (ADC)',
      summary: 'An ADC encodes an analog signal as binary data so digital circuits can process real-world input.',
      examples: ['Converting a microphone or sensor signal for a computer or microcontroller.'],
      recallPrompt: 'Why is an ADC needed when a digital system reads a sensor?',
      recallAnswer: 'It converts the sensor’s analog signal into binary data the digital system can process.',
    },
    {
      id: 'modulation',
      title: 'Modulation',
      summary: 'Modulation adds information to an electrical or optical carrier signal so data can be transformed into radio waves.',
      bullets: ['A carrier has a consistent frequency and amplitude before information changes one of its properties.'],
      recallPrompt: 'What does modulation add to a carrier signal?',
      recallAnswer: 'Information, by varying a property of the carrier signal.',
    },
    {
      id: 'amplitude-modulation',
      title: 'Amplitude Modulation (AM)',
      summary: 'AM varies the carrier signal’s amplitude in proportion to the analog message signal.',
      recallPrompt: 'Which carrier property changes in amplitude modulation?',
      recallAnswer: 'Amplitude.',
    },
    {
      id: 'frequency-modulation',
      title: 'Frequency Modulation (FM)',
      summary: 'FM varies the carrier signal’s frequency in proportion to the analog message signal.',
      recallPrompt: 'Which carrier property changes in frequency modulation?',
      recallAnswer: 'Frequency.',
    },
    {
      id: 'phase-modulation',
      title: 'Phase Modulation (PM)',
      summary: 'PM varies the carrier signal’s phase in proportion to the analog message signal.',
      recallPrompt: 'Which carrier property changes in phase modulation?',
      recallAnswer: 'Phase.',
    },
    {
      id: 'amplitude-shift-keying',
      title: 'Amplitude-Shift Keying (ASK)',
      summary: 'ASK varies the carrier amplitude according to digital data.',
      recallPrompt: 'Which digital modulation technique represents data by changing amplitude?',
      recallAnswer: 'Amplitude-Shift Keying (ASK).',
    },
    {
      id: 'frequency-shift-keying',
      title: 'Frequency-Shift Keying (FSK)',
      summary: 'FSK changes the carrier frequency to represent digital data.',
      recallPrompt: 'Which digital modulation technique represents data by changing frequency?',
      recallAnswer: 'Frequency-Shift Keying (FSK).',
    },
    {
      id: 'phase-shift-keying',
      title: 'Phase-Shift Keying (PSK)',
      summary: 'PSK shifts the carrier phase to represent digital data.',
      recallPrompt: 'Which digital modulation technique represents data by shifting phase?',
      recallAnswer: 'Phase-Shift Keying (PSK).',
    },
  ],
};
