import type { TheoryTerm } from '../types';

const term = (id: string, module: TheoryTerm['module'], answer: string, displayAnswer: string, clue: string): TheoryTerm => ({ id, module, answer, displayAnswer, clue });

export const cs412Terms: readonly TheoryTerm[] = [
  term('data-mining', 'introduction', 'DATA MINING', 'Data mining', 'The process of examining large datasets to discover useful patterns and relationships.'),
  term('classification', 'introduction', 'CLASSIFICATION', 'Classification', 'Assigning data points to predefined categories according to their characteristics.'),
  term('clustering', 'introduction', 'CLUSTERING', 'Clustering', 'Grouping similar data points together without relying on predefined category labels.'),
  term('prediction', 'introduction', 'PREDICTION', 'Prediction', 'Examining patterns and trends to estimate the probability of a future outcome.'),
  term('regression', 'introduction', 'REGRESSION', 'Regression', 'A technique used to identify and analyze relationships between numeric variables.'),
  term('association-rules', 'introduction', 'ASSOCIATION RULES', 'Association rules', 'Rules that uncover correlations or items that frequently occur together in a dataset.'),
  term('telecommunications', 'introduction', 'TELECOMMUNICATIONS', 'Telecommunications', 'Industry that mines customer behavior to target advertisements and campaigns.'),
  term('insurance', 'introduction', 'INSURANCE', 'Insurance', 'Industry that uses data mining for fraudulent-claim detection and risk management.'),
  term('finance', 'introduction', 'FINANCE', 'Finance', 'Industry that mines data to evaluate market risk and improve investment returns.'),
  term('retail', 'introduction', 'RETAIL', 'Retail', 'Industry that analyzes joint purchases to arrange products on shelves and aisles.'),
  term('healthcare', 'introduction', 'HEALTHCARE', 'Healthcare', 'Field that mines medical histories and treatments to improve diagnostic accuracy.'),
  term('manufacturing', 'introduction', 'MANUFACTURING', 'Manufacturing', 'Industry that predicts supply needs and equipment failure for just-in-time fulfillment.'),
  term('crisp-dm', 'crisp-dm', 'CRISP DM', 'CRISP-DM', 'Acronym for the Cross-Industry Standard Process for Data Mining methodology.'),
  term('process-model', 'crisp-dm', 'PROCESS MODEL', 'Process model', 'A structured description of typical project phases, their tasks, and relationships.'),
  term('business-understanding', 'crisp-dm', 'BUSINESS UNDERSTANDING', 'Business understanding', 'First CRISP-DM phase that identifies the project objectives, scope, question, or problem.'),
  term('data-understanding', 'crisp-dm', 'DATA UNDERSTANDING', 'Data understanding', 'CRISP-DM phase where relevant data is collected and explored after the problem is understood.'),
  term('data-preparation', 'crisp-dm', 'DATA PREPARATION', 'Data preparation', 'CRISP-DM phase that builds the final relevant dataset for model creation.'),
  term('modeling', 'crisp-dm', 'MODELING', 'Modeling', 'CRISP-DM phase that selects and applies suitable analytical techniques to the data.'),
  term('evaluation', 'crisp-dm', 'EVALUATION', 'Evaluation', 'CRISP-DM phase that tests whether a model answers the original business question.'),
  term('deployment', 'crisp-dm', 'DEPLOYMENT', 'Deployment', 'Final CRISP-DM phase that puts results into use or reports them to stakeholders.'),
  term('stakeholders', 'crisp-dm', 'STAKEHOLDERS', 'Stakeholders', 'People with an interest in the project who define needs or receive its results.'),
  term('project-objectives', 'crisp-dm', 'PROJECT OBJECTIVES', 'Project objectives', 'Specific goals identified at the beginning of a comprehensive data-mining project.'),
  term('project-scope', 'crisp-dm', 'PROJECT SCOPE', 'Project scope', 'The boundaries and extent of work established during business understanding.'),
  term('relevant-data', 'crisp-dm', 'RELEVANT DATA', 'Relevant data', 'Information collected because it can help answer the defined business question.'),
  term('predictive-model', 'crisp-dm', 'PREDICTIVE MODEL', 'Predictive model', 'A modeling technique that uses patterns in known data to estimate unknown outcomes.'),
  term('estimation', 'crisp-dm', 'ESTIMATION', 'Estimation', 'A modeling technique that calculates an approximate value for an unknown quantity.'),
  term('data-warehouse', 'warehousing', 'DATA WAREHOUSE', 'Data warehouse', 'A central archive of historical organizational data designed for analysis and decisions.'),
  term('historical-data', 'warehousing', 'HISTORICAL DATA', 'Historical data', 'Information retained over time so earlier conditions and trends can be analyzed.'),
  term('decision-making', 'warehousing', 'DECISION MAKING', 'Decision-making', 'The organizational purpose supported by retrieving and analyzing warehoused information.'),
  term('database', 'warehousing', 'DATABASE', 'Database', 'A transactional system that updates current data and keeps the most recent values available.'),
  term('transactional-system', 'warehousing', 'TRANSACTIONAL SYSTEM', 'Transactional system', 'A system optimized to monitor and update real-time operational records.'),
  term('real-time-data', 'warehousing', 'REAL TIME DATA', 'Real-time data', 'Current information updated as transactions happen rather than stored mainly as history.'),
  term('data-lake', 'warehousing', 'DATA LAKE', 'Data lake', 'A repository that holds accessible raw data whose eventual purpose may not yet be known.'),
  term('raw-data', 'warehousing', 'RAW DATA', 'Raw data', 'Unrefined information stored before filtering, cleaning, or modeling.'),
  term('refined-data', 'warehousing', 'REFINED DATA', 'Refined data', 'Filtered and prepared information held for a specific analytical purpose.'),
  term('data-mart', 'warehousing', 'DATA MART', 'Data mart', 'A smaller, faster warehouse subset focused on one department or subject area.'),
  term('subject-area', 'warehousing', 'SUBJECT AREA', 'Subject area', 'A focused business domain, such as sales, served by a data mart.'),
  term('data-refresh', 'warehousing', 'DATA REFRESH', 'Data refresh', 'The operation that periodically updates warehouse data from multiple sources.'),
  term('data-cleaning', 'warehousing', 'DATA CLEANING', 'Data cleaning', 'The operation that removes inconsistencies and rectifies noisy or erroneous information.'),
  term('data-extraction', 'warehousing', 'DATA EXTRACTION', 'Data extraction', 'The operation that retrieves relevant source information for organization and mining.'),
  term('data-transformation', 'warehousing', 'DATA TRANSFORMATION', 'Data transformation', 'The operation that converts source structures into the warehouse target structure.'),
  term('data-loading', 'warehousing', 'DATA LOADING', 'Data loading', 'The operation that places prepared information into its target repository.'),
  term('single-tier', 'warehousing', 'SINGLE TIER ARCHITECTURE', 'Single-tier architecture', 'Warehouse architecture that attempts to reduce redundancy with a single data layer.'),
  term('two-tier', 'warehousing', 'TWO TIER ARCHITECTURE', 'Two-tier architecture', 'Warehouse architecture where analytical clients communicate directly with the server layer.'),
  term('three-tier', 'warehousing', 'THREE TIER ARCHITECTURE', 'Three-tier architecture', 'Architecture with source, reconciled, and warehouse tiers suited to long-lived systems.'),
  term('source-layer', 'warehousing', 'SOURCE LAYER', 'Source layer', 'Architecture layer where point-of-sale, marketing, CRM, and ERP systems feed data.'),
  term('staging-layer', 'warehousing', 'STAGING LAYER', 'Staging layer', 'Landing area that ingests source data before business rules and transformations are applied.'),
  term('warehouse-layer', 'warehousing', 'WAREHOUSE LAYER', 'Warehouse layer', 'Layer where integrated, modeled, subject-oriented, time-variant information is stored.'),
  term('consumption-layer', 'warehousing', 'CONSUMPTION LAYER', 'Consumption layer', 'Analytics layer where warehouse information is modeled for tools and business users.'),
  term('system-of-record', 'warehousing', 'SYSTEM OF RECORD', 'System of record', 'Authoritative source system from which the staging area ingests data.'),
  term('subject-oriented', 'warehousing', 'SUBJECT ORIENTED', 'Subject-oriented', 'Warehouse quality meaning information is organized around major business subjects.'),
  term('integrated', 'warehousing', 'INTEGRATED', 'Integrated', 'Warehouse quality meaning information from different sources is made consistent.'),
  term('time-variant', 'warehousing', 'TIME VARIANT', 'Time-variant', 'Warehouse quality meaning records preserve changes and history across time.'),
  term('non-volatile', 'warehousing', 'NON VOLATILE', 'Non-volatile', 'Warehouse quality meaning stored historical information is stable and not routinely overwritten.'),
  term('crm', 'warehousing', 'CRM', 'CRM', 'Customer relationship management system that can feed the warehouse source layer.'),
  term('erp', 'warehousing', 'ERP', 'ERP', 'Enterprise resource planning system that can supply data to the source layer.'),
] as const;
